/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  index: {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    meta: undefined,
  },
  android: {
    name: "android",
    description:
      "A spotlight effect that follows your mouse cursor and highlights borders on hover.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "apps/v4/registry/magicui-v4/android.tsx",
        type: "registry:ui",
        target: "components/magicui/android.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/apps/v4/registry/magicui-v4/android.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  utils: {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "apps/v4/registry/lib/utils.ts",
        type: "registry:lib",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/apps/v4/registry/lib/utils.ts");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "android-demo": {
    name: "android-demo",
    description: "Example showing a mockup of an Android device.",
    type: "registry:example",
    registryDependencies: ["https://magicui.design/r/android"],
    files: [
      {
        path: "apps/v4/registry/example-v4/android-demo.tsx",
        type: "registry:example",
        target: "components/android-demo.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/apps/v4/registry/example-v4/android-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
  "android-demo-2": {
    name: "android-demo-2",
    description: "Example showing a mockup of an Android device.",
    type: "registry:example",
    registryDependencies: ["https://magicui.design/r/android"],
    files: [
      {
        path: "apps/v4/registry/example-v4/android-demo-2.tsx",
        type: "registry:example",
        target: "components/android-demo-2.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/apps/v4/registry/example-v4/android-demo-2.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    meta: undefined,
  },
};
