name: MagicUI Auto Merge by Unnamed
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  automerge:
    name: MagicUI Auto Merge
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_REQUIRED_APPROVALS: "2"
