name: MagicUI Linter by Unnamed
run-name: ${{ github.actor }} is attempting to make a ${{github.event_name}}.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: Run Linters
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: write

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: ^9

      - name: Install dependencies
        run: pnpm install

      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          git_name: "MagicUI Lint"
          auto_fix: true
          continue_on_error: true
          neutral_check_on_warning: true
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          prettier: true
          prettier_extensions: css,html,js,json,jsx,md,sass,scss,ts,tsx,vue
          prettier_auto_fix: true
          eslint: true
          eslint_auto_fix: true
          commit_message: "[fix] codebase style issues with ${linter}"
